require('jest-fetch-mock').enableMocks();

fetchMock.mockIf(/^https?:\/\/dev.devtest.vegas.*$/, (req) => {
	if (req.url.endsWith('/city.json')) {
		return Promise.resolve({
			body: JSON.stringify([]),
			headers: {
				'Content-Type': 'application/json',
			},
		});
	} else if (req.url.endsWith('/state.json')) {
		return Promise.resolve({
			body: JSON.stringify([
				{ name: 'Alberta', countryCode: 'CA' },
				{ name: 'British Columbia', countryCode: 'CA' },
				{ name: 'Manitoba', countryCode: 'CA' },
				{ name: 'New Brunswick', countryCode: 'CA' },
				{ name: 'Newfoundland and Labrador', countryCode: 'CA' },
				{ name: 'Northwest Territories', countryCode: 'CA' },
				{ name: 'Nova Scotia', countryCode: 'CA' },
				{ name: 'Nunavut', countryCode: 'CA' },
				{ name: 'Ontario', countryCode: 'CA' },
				{ name: 'Prince Edward Island', countryCode: 'CA' },
				{ name: 'Quebec', countryCode: 'CA' },
				{ name: 'Saskatchewan', countryCode: 'CA' },
				{ name: 'Yukon', countryCode: 'CA' },
				{ name: 'Alabama', countryCode: 'US' },
				{ name: 'Alaska', countryCode: 'US' },
				{ name: 'American Samoa', countryCode: 'US' },
				{ name: 'Arizona', countryCode: 'US' },
				{ name: 'Arkansas', countryCode: 'US' },
				{ name: 'Baker Island', countryCode: 'US' },
				{ name: 'California', countryCode: 'US' },
				{ name: 'Colorado', countryCode: 'US' },
				{ name: 'Connecticut', countryCode: 'US' },
				{ name: 'Delaware', countryCode: 'US' },
				{ name: 'District of Columbia', countryCode: 'US' },
				{ name: 'Florida', countryCode: 'US' },
				{ name: 'Georgia', countryCode: 'US' },
				{ name: 'Guam', countryCode: 'US' },
				{ name: 'Hawaii', countryCode: 'US' },
				{ name: 'Howland Island', countryCode: 'US' },
				{ name: 'Idaho', countryCode: 'US' },
				{ name: 'Illinois', countryCode: 'US' },
				{ name: 'Indiana', countryCode: 'US' },
				{ name: 'Iowa', countryCode: 'US' },
				{ name: 'Jarvis Island', countryCode: 'US' },
				{ name: 'Johnston Atoll', countryCode: 'US' },
				{ name: 'Kansas', countryCode: 'US' },
				{ name: 'Kentucky', countryCode: 'US' },
				{ name: 'Kingman Reef', countryCode: 'US' },
				{ name: 'Louisiana', countryCode: 'US' },
				{ name: 'Maine', countryCode: 'US' },
				{ name: 'Maryland', countryCode: 'US' },
				{ name: 'Massachusetts', countryCode: 'US' },
				{ name: 'Michigan', countryCode: 'US' },
				{ name: 'Midway Atoll', countryCode: 'US' },
				{ name: 'Minnesota', countryCode: 'US' },
				{ name: 'Mississippi', countryCode: 'US' },
				{ name: 'Missouri', countryCode: 'US' },
				{ name: 'Montana', countryCode: 'US' },
				{ name: 'Navassa Island', countryCode: 'US' },
				{ name: 'Nebraska', countryCode: 'US' },
				{ name: 'Nevada', countryCode: 'US' },
				{ name: 'New Hampshire', countryCode: 'US' },
				{ name: 'New Jersey', countryCode: 'US' },
				{ name: 'New Mexico', countryCode: 'US' },
				{ name: 'New York', countryCode: 'US' },
				{ name: 'North Carolina', countryCode: 'US' },
				{ name: 'North Dakota', countryCode: 'US' },
				{ name: 'Northern Mariana Islands', countryCode: 'US' },
				{ name: 'Ohio', countryCode: 'US' },
				{ name: 'Oklahoma', countryCode: 'US' },
				{ name: 'Oregon', countryCode: 'US' },
				{ name: 'Palmyra Atoll', countryCode: 'US' },
				{ name: 'Pennsylvania', countryCode: 'US' },
				{ name: 'Puerto Rico', countryCode: 'US' },
				{ name: 'Rhode Island', countryCode: 'US' },
				{ name: 'South Carolina', countryCode: 'US' },
				{ name: 'South Dakota', countryCode: 'US' },
				{ name: 'Tennessee', countryCode: 'US' },
				{ name: 'Texas', countryCode: 'US' },
				{ name: 'United States Minor Outlying Islands', countryCode: 'US' },
				{ name: 'United States Virgin Islands', countryCode: 'US' },
				{ name: 'Utah', countryCode: 'US' },
				{ name: 'Vermont', countryCode: 'US' },
				{ name: 'Virginia', countryCode: 'US' },
				{ name: 'Wake Island', countryCode: 'US' },
				{ name: 'Washington', countryCode: 'US' },
				{ name: 'West Virginia', countryCode: 'US' },
				{ name: 'Wisconsin', countryCode: 'US' },
				{ name: 'Wyoming', countryCode: 'US' },
			]),
			headers: {
				'Content-Type': 'application/json',
			},
		});
	} else if (req.url.endsWith('/country.json')) {
		return Promise.resolve({
			body: JSON.stringify([
				{
					name: 'Canada',
					phonecode: '1',
					isoCode: 'CA',
					flag: '🇨🇦',
					currency: 'CAD',
					latitude: '60.00000000',
					longitude: '-95.00000000',
					timezones: [
						{
							zoneName: 'America/Atikokan',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America)',
						},
						{
							zoneName: 'America/Blanc-Sablon',
							gmtOffset: -14400,
							gmtOffsetName: 'UTC-04:00',
							abbreviation: 'AST',
							tzName: 'Atlantic Standard Time',
						},
						{
							zoneName: 'America/Cambridge_Bay',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America)',
						},
						{
							zoneName: 'America/Creston',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America)',
						},
						{
							zoneName: 'America/Dawson',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America)',
						},
						{
							zoneName: 'America/Dawson_Creek',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America)',
						},
						{
							zoneName: 'America/Edmonton',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America)',
						},
						{
							zoneName: 'America/Fort_Nelson',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America)',
						},
						{
							zoneName: 'America/Glace_Bay',
							gmtOffset: -14400,
							gmtOffsetName: 'UTC-04:00',
							abbreviation: 'AST',
							tzName: 'Atlantic Standard Time',
						},
						{
							zoneName: 'America/Goose_Bay',
							gmtOffset: -14400,
							gmtOffsetName: 'UTC-04:00',
							abbreviation: 'AST',
							tzName: 'Atlantic Standard Time',
						},
						{
							zoneName: 'America/Halifax',
							gmtOffset: -14400,
							gmtOffsetName: 'UTC-04:00',
							abbreviation: 'AST',
							tzName: 'Atlantic Standard Time',
						},
						{
							zoneName: 'America/Inuvik',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America',
						},
						{
							zoneName: 'America/Iqaluit',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Moncton',
							gmtOffset: -14400,
							gmtOffsetName: 'UTC-04:00',
							abbreviation: 'AST',
							tzName: 'Atlantic Standard Time',
						},
						{
							zoneName: 'America/Nipigon',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Pangnirtung',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Rainy_River',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Rankin_Inlet',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Regina',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Resolute',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/St_Johns',
							gmtOffset: -12600,
							gmtOffsetName: 'UTC-03:30',
							abbreviation: 'NST',
							tzName: 'Newfoundland Standard Time',
						},
						{
							zoneName: 'America/Swift_Current',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Thunder_Bay',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Toronto',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Vancouver',
							gmtOffset: -28800,
							gmtOffsetName: 'UTC-08:00',
							abbreviation: 'PST',
							tzName: 'Pacific Standard Time (North America',
						},
						{
							zoneName: 'America/Whitehorse',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America',
						},
						{
							zoneName: 'America/Winnipeg',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Yellowknife',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America',
						},
					],
				},
				{
					isoCode: 'US',
					name: 'United States',
					phonecode: '1',
					flag: '🇺🇸',
					currency: 'USD',
					latitude: '38.00000000',
					longitude: '-97.00000000',
					timezones: [
						{
							zoneName: 'America/Adak',
							gmtOffset: -36000,
							gmtOffsetName: 'UTC-10:00',
							abbreviation: 'HST',
							tzName: 'Hawaii–Aleutian Standard Time',
						},
						{
							zoneName: 'America/Anchorage',
							gmtOffset: -32400,
							gmtOffsetName: 'UTC-09:00',
							abbreviation: 'AKST',
							tzName: 'Alaska Standard Time',
						},
						{
							zoneName: 'America/Boise',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America',
						},
						{
							zoneName: 'America/Chicago',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Denver',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America',
						},
						{
							zoneName: 'America/Detroit',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Indianapolis',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Knox',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Marengo',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Petersburg',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Tell_City',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Vevay',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Vincennes',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Indiana/Winamac',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Juneau',
							gmtOffset: -32400,
							gmtOffsetName: 'UTC-09:00',
							abbreviation: 'AKST',
							tzName: 'Alaska Standard Time',
						},
						{
							zoneName: 'America/Kentucky/Louisville',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Kentucky/Monticello',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Los_Angeles',
							gmtOffset: -28800,
							gmtOffsetName: 'UTC-08:00',
							abbreviation: 'PST',
							tzName: 'Pacific Standard Time (North America',
						},
						{
							zoneName: 'America/Menominee',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Metlakatla',
							gmtOffset: -32400,
							gmtOffsetName: 'UTC-09:00',
							abbreviation: 'AKST',
							tzName: 'Alaska Standard Time',
						},
						{
							zoneName: 'America/New_York',
							gmtOffset: -18000,
							gmtOffsetName: 'UTC-05:00',
							abbreviation: 'EST',
							tzName: 'Eastern Standard Time (North America',
						},
						{
							zoneName: 'America/Nome',
							gmtOffset: -32400,
							gmtOffsetName: 'UTC-09:00',
							abbreviation: 'AKST',
							tzName: 'Alaska Standard Time',
						},
						{
							zoneName: 'America/North_Dakota/Beulah',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/North_Dakota/Center',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/North_Dakota/New_Salem',
							gmtOffset: -21600,
							gmtOffsetName: 'UTC-06:00',
							abbreviation: 'CST',
							tzName: 'Central Standard Time (North America',
						},
						{
							zoneName: 'America/Phoenix',
							gmtOffset: -25200,
							gmtOffsetName: 'UTC-07:00',
							abbreviation: 'MST',
							tzName: 'Mountain Standard Time (North America',
						},
						{
							zoneName: 'America/Sitka',
							gmtOffset: -32400,
							gmtOffsetName: 'UTC-09:00',
							abbreviation: 'AKST',
							tzName: 'Alaska Standard Time',
						},
						{
							zoneName: 'America/Yakutat',
							gmtOffset: -32400,
							gmtOffsetName: 'UTC-09:00',
							abbreviation: 'AKST',
							tzName: 'Alaska Standard Time',
						},
						{
							zoneName: 'Pacific/Honolulu',
							gmtOffset: -36000,
							gmtOffsetName: 'UTC-10:00',
							abbreviation: 'HST',
							tzName: 'Hawaii–Aleutian Standard Time',
						},
					],
				},
			]),
			headers: {
				'Content-Type': 'application/json',
			},
		});
	} else {
		return Promise.resolve({
			status: 404,
			body: 'Not Found',
		});
	}
});
